# Setup
title: OK's Space Conquest Project
description: Zoooooooom
url: https://hhan-a.github.io
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: hhan-a
  card: summary
logo: logo.png
social:
  name: Kim Han a
  links:
    - https://www.instagram.com/han_ok2
    - https://github.com/hhan-a
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-FXBBSXQNZ7

# Replace this value and uncomment to enable Disqus
disqus: hhan-a

# Specify the author for blog posts
author:
  name: hhan-a
  url: https://github.com/hhan-a
  email: ujb773@gmail.com
